/* Chapter 1 quiz. Each question: q, options (4), answer (0-3), explain, section (textbook anchor id).
   All questions are original practice items; companies and numbers are fictional. */
window.QUIZ = {
  chapter: "ch1",
  title: "Chapter 1: Managerial Accounting and Cost Concepts",
  textbook: "textbook.html",
  questions: [
    /* ---- 1.1 ---- */
    { q: "Managerial accounting mainly serves:",
      options: ["Outside investors and creditors deciding whether to lend", "Managers and employees inside the organization", "Tax authorities checking taxable income", "Stock exchange regulators"], answer: 1,
      explain: "Managerial accounting gives insiders the information they need to plan, control and make decisions. Financial accounting is the one aimed at outsiders.",
      section: "s1-1-what" },
    { q: "Which statement describes managerial accounting rather than financial accounting?",
      options: ["It must follow generally accepted accounting principles", "It reports on the company as a whole", "It emphasizes relevance and looks to the future", "It is required for every publicly traded company"], answer: 2,
      explain: "Managerial accounting is about future plans and decisions, so relevance and timeliness matter more than precision. It is optional, has no GAAP requirement and often reports on segments.",
      section: "s1-1-what" },
    { q: "A factory makes three kayak models in one building. If the cost object is a single kayak, the factory rent is:",
      options: ["An indirect cost", "A direct cost", "A selling cost", "A period cost"], answer: 0,
      explain: "The rent supports all three models at once and can't be easily traced to one kayak, so it is an indirect (common) cost. It is still a manufacturing cost, not a selling or period cost.",
      section: "s1-1-objects" },
    { q: "The salary of a manager who runs one factory is best described as:",
      options: ["Direct to every unit the factory makes", "Indirect to the factory, because it is a salary", "Direct to the factory, but indirect to each unit", "A sunk cost that can be ignored"], answer: 2,
      explain: "Direct and indirect depend on the cost object. The salary is easily traced to the factory as a whole, but it can't be traced to any single unit.",
      section: "s1-1-objects" },

    /* ---- 1.2 ---- */
    { q: "A furniture maker uses small amounts of glue and screws that would be too costly to trace to each chair. These are classified as:",
      options: ["Direct materials", "Direct labor", "A selling cost", "Manufacturing overhead"], answer: 3,
      explain: "They are indirect materials. Materials that can't be easily traced to units go into manufacturing overhead.",
      section: "s1-2-mfg" },
    { q: "Which of these is direct labor?",
      options: ["Wages of the factory's night security guard", "Salary of the factory supervisor", "Wages of the workers who operate the molds", "Commissions paid to the company's salespeople"], answer: 2,
      explain: "Mold operators work on individual units, so their wages are easily traced. The guard and the supervisor are indirect labor (overhead), and commissions are a selling cost.",
      section: "s1-2-mfg" },
    { q: "A company reports direct materials of $30,000, direct labor of $20,000 and manufacturing overhead of $25,000. What is its prime cost?",
      options: ["$45,000", "$50,000", "$55,000", "$75,000"], answer: 1,
      explain: "Prime cost = direct materials + direct labor = $30,000 + $20,000 = $50,000.",
      section: "s1-2-prime" },
    { q: "Using the same figures (DM $30,000, DL $20,000, MOH $25,000), what is the conversion cost?",
      options: ["$45,000", "$50,000", "$55,000", "$75,000"], answer: 0,
      explain: "Conversion cost = direct labor + manufacturing overhead = $20,000 + $25,000 = $45,000. Direct labor is part of both prime and conversion cost.",
      section: "s1-2-prime" },
    { q: "Rent on a company's head office, in a separate building from the factory, is:",
      options: ["Manufacturing overhead", "Direct materials", "A conversion cost", "An administrative cost"], answer: 3,
      explain: "The head office runs the company as a whole and has nothing to do with making the product, so its rent is an administrative cost. Rent on the factory would be overhead.",
      section: "s1-2-nonmfg" },

    /* ---- 1.3 ---- */
    { q: "Product costs include:",
      options: ["Only direct materials and direct labor, nothing else", "Direct materials, direct labor and manufacturing overhead", "Every cost the company incurs during the period", "Selling and administrative costs"], answer: 1,
      explain: "All three manufacturing costs are product (inventoriable) costs. Selling and administrative costs are period costs.",
      section: "s1-3-product" },
    { q: "Period costs are:",
      options: ["Expensed in the period they are incurred", "Recorded as inventory until the product is sold", "Never expensed", "Added to cost of goods sold"], answer: 0,
      explain: "Selling and administrative costs go straight to the income statement in the period they occur, whether or not anything was sold.",
      section: "s1-3-product" },
    { q: "A company made 2,000 units with a product cost of $40 each and sold 1,500 of them. What is cost of goods sold?",
      options: ["$20,000", "$80,000", "$40,000", "$60,000"], answer: 3,
      explain: "Only the units sold are expensed: 1,500 × $40 = $60,000. The other 500 units stay in finished goods inventory.",
      section: "s1-3-flow" },
    { q: "In the same company (2,000 made at $40, 1,500 sold), what is ending finished goods inventory?",
      options: ["$20,000", "$60,000", "$80,000", "$40,000"], answer: 0,
      explain: "The 500 unsold units stay on the balance sheet: 500 × $40 = $20,000.",
      section: "s1-3-flow" },

    /* ---- 1.4 ---- */
    { q: "As activity increases within the relevant range, variable cost per unit:",
      options: ["Increases", "Decreases", "Stays the same", "Doubles"], answer: 2,
      explain: "Variable costs change in total but stay constant per unit.",
      section: "s1-4-variable" },
    { q: "As activity increases within the relevant range, fixed cost per unit:",
      options: ["Decreases", "Increases", "Stays the same", "Turns into a variable cost"], answer: 0,
      explain: "The same total fixed cost is spread over more units, so the cost per unit falls.",
      section: "s1-4-fixed" },
    { q: "A factory lease costs $9,000 a month, which is $15 a unit at 600 units. If production rises to 900 units (still in the relevant range), the total lease cost is:",
      options: ["$13,500", "$9,000", "$6,000", "$10,000"], answer: 1,
      explain: "A fixed cost stays the same in total, so it is still $9,000. Multiplying $15 by 900 is the classic trap; per unit it would now be $10.",
      section: "s1-4-fixed" },
    { q: "Which of these is a discretionary fixed cost?",
      options: ["Depreciation on the factory building", "Property taxes on the plant", "This year's advertising campaign", "Lease payments on equipment"], answer: 2,
      explain: "Advertising is set by a yearly management decision and can be cut for a while without lasting damage. The others are committed fixed costs.",
      section: "s1-4-fixed" },
    { q: "The relevant range is:",
      options: ["The band of activity where the cost behavior assumptions hold", "The range of prices that customers are willing to accept", "The time period that a budget covers", "The difference between the highest and lowest costs of the year"], answer: 0,
      explain: "Inside the relevant range a fixed cost stays fixed and a variable rate stays constant. Outside it, for example when a second building is needed, the costs change.",
      section: "s1-4-range" },
    { q: "Monthly maintenance cost follows Y = $1,500 + $3X, where X is machine hours. What is the total cost at 800 machine hours?",
      options: ["$2,400", "$3,900", "$4,500", "$1,500"], answer: 1,
      explain: "Y = $1,500 + $3 × 800 = $1,500 + $2,400 = $3,900. The $1,500 is the fixed part and $2,400 the variable part.",
      section: "s1-4-mixed" },

    /* ---- 1.5 ---- */
    { q: "A cost that has already been incurred and cannot be changed by any decision is a:",
      options: ["Opportunity cost", "Differential cost", "Sunk cost", "Variable cost"], answer: 2,
      explain: "Sunk costs are gone whatever you decide, so they are never relevant.",
      section: "s1-5-sunk" },
    { q: "Which statement about opportunity cost is true?",
      options: ["It is recorded in the general ledger like any other cost", "It is always a fixed cost", "It is another name for a sunk cost from a past decision", "It is the benefit given up by choosing one option"], answer: 3,
      explain: "An opportunity cost is never recorded in the accounting records, but it belongs in the decision.",
      section: "s1-5-opp" },
    { q: "Option A brings $50,000 of revenue and $30,000 of costs. Option B brings $58,000 of revenue and $35,000 of costs. By how much is Option B better?",
      options: ["$8,000", "$5,000", "$3,000", "$28,000"], answer: 2,
      explain: "Differential revenue is $8,000 and differential cost is $5,000, so B is better by $8,000 − $5,000 = $3,000.",
      section: "s1-5-diff" },

    /* ---- 1.6 ---- */
    { q: "Contribution margin equals:",
      options: ["Sales − cost of goods sold", "Sales − all variable expenses", "Sales − fixed expenses", "Gross margin − selling expenses"], answer: 1,
      explain: "Contribution margin subtracts every variable expense, including variable selling and administrative costs. Sales − cost of goods sold is gross margin.",
      section: "s1-6-formats" },
    { q: "The traditional income statement format organizes costs by:",
      options: ["Behavior", "Segment", "Amount", "Function"], answer: 3,
      explain: "The traditional format groups costs by function (cost of goods sold, selling, administrative). The contribution format groups them by behavior (variable vs fixed).",
      section: "s1-6-formats" },
    { q: "A retailer has sales of $200,000, cost of goods sold of $120,000 (all variable), variable selling expenses of $10,000 and fixed expenses of $50,000. What is its contribution margin?",
      options: ["$80,000", "$70,000", "$20,000", "$30,000"], answer: 1,
      explain: "Variable expenses are $120,000 + $10,000 = $130,000, so contribution margin = $200,000 − $130,000 = $70,000. Subtract the $50,000 fixed and net operating income is $20,000.",
      section: "s1-6-formats" }
  ]
};
