/* Chapter 5 quiz. Each question: q, options (4), answer (0-3), explain, section (textbook anchor id).
   All questions are original practice items; companies and numbers are fictional. */
window.QUIZ = {
  chapter: "ch5",
  title: "Chapter 5: Cost-Volume-Profit Relationships",
  textbook: "textbook.html",
  questions: [
    /* ---- 5.1 ---- */
    { q: "Which of these is an assumption of CVP analysis?",
      options: ["Selling price per unit falls as more units are sold", "Total fixed costs rise in step with every unit that is sold", "Variable cost per unit stays constant in the relevant range", "Inventory levels rise and fall widely from month to month"], answer: 2,
      explain: "CVP assumes linear costs: the same variable cost per unit and the same total fixed cost within the relevant range, a constant price, and no change in inventories.",
      section: "s5-1-assume" },
    { q: "A product sells for $50 and has variable expenses of $35 per unit. What is the contribution margin ratio?",
      options: ["70%", "30%", "15%", "35%"], answer: 1,
      explain: "Unit CM = $50 − $35 = $15. CM ratio = $15 ÷ $50 = 30%. (70% is the variable expense ratio.)",
      section: "s5-1-ratio" },
    { q: "Contribution margin is:",
      options: ["Sales minus cost of goods sold", "Sales minus all variable expenses", "Sales minus fixed expenses", "Net operating income plus variable expenses"], answer: 1,
      explain: "Contribution margin is what's left of sales after every variable expense. It covers fixed expenses first, then becomes profit.",
      section: "s5-1-cm" },
    { q: "A company's CM ratio is 30%, and its sales rise by $50,000 with no change in fixed expenses. By how much will net operating income increase?",
      options: ["$50,000", "$35,000", "$15,000", "$3,000"], answer: 2,
      explain: "Change in CM = $50,000 × 30% = $15,000. With fixed expenses unchanged, net operating income rises by the same $15,000.",
      section: "s5-1-ratio" },
    { q: "A company's variable expense ratio is 65%. What is its CM ratio?",
      options: ["35%", "65%", "100%", "130%"], answer: 0,
      explain: "The two ratios always add to 100%: 100% − 65% = 35%.",
      section: "s5-1-ratio" },

    /* ---- 5.2 ---- */
    { q: "Contribution margin is $90,000 and net operating income is $30,000. What is the degree of operating leverage?",
      options: ["0.33", "$60,000", "120%", "3"], answer: 3,
      explain: "Degree of operating leverage = CM ÷ NOI = $90,000 ÷ $30,000 = 3.",
      section: "s5-2" },
    { q: "A company's degree of operating leverage is 4. If sales increase by 10%, net operating income will increase by:",
      options: ["10%", "4%", "40%", "14%"], answer: 2,
      explain: "% change in NOI = DOL × % change in sales = 4 × 10% = 40%.",
      section: "s5-2" },
    { q: "Which company is likely to have the highest operating leverage?",
      options: ["One with high fixed costs and low variable costs", "One with low fixed costs and high variable costs", "One with no fixed costs at all", "One with the highest sales revenue"], answer: 0,
      explain: "High fixed costs and a large CM per unit make profit swing sharply when sales change.",
      section: "s5-2" },

    /* ---- 5.3 ---- */
    { q: "A product sells for $40, variable expenses are $28 per unit, and fixed expenses are $60,000. What is the break-even point in units?",
      options: ["1,500 units", "2,143 units", "5,000 units", "6,000 units"], answer: 2,
      explain: "Unit CM = $40 − $28 = $12. Break-even = $60,000 ÷ $12 = 5,000 units.",
      section: "s5-3-be" },
    { q: "A company's CM ratio is 35% and its fixed expenses are $140,000. What is the break-even point in sales dollars?",
      options: ["$49,000", "$400,000", "$215,385", "$140,000"], answer: 1,
      explain: "Break-even sales = fixed expenses ÷ CM ratio = $140,000 ÷ 35% = $400,000. ($215,385 divides by the variable expense ratio by mistake.)",
      section: "s5-3-be" },
    { q: "Sales are $400,000 and break-even sales are $300,000. What is the margin of safety percentage?",
      options: ["33%", "75%", "$100,000", "25%"], answer: 3,
      explain: "Margin of safety = $400,000 − $300,000 = $100,000, and $100,000 ÷ $400,000 of current sales = 25%.",
      section: "s5-3-mos" },
    { q: "At the break-even point:",
      options: ["Contribution margin equals fixed expenses", "Sales equal variable expenses", "Fixed expenses are zero", "Net operating income equals contribution margin"], answer: 0,
      explain: "Profit is zero when total contribution margin exactly covers fixed expenses.",
      section: "s5-3-be" },

    /* ---- 5.4 ---- */
    { q: "A product sells for $30, variable expenses are $18 per unit, and fixed expenses are $42,000. How many units must be sold to earn a target profit of $18,000?",
      options: ["3,500 units", "1,500 units", "2,000 units", "5,000 units"], answer: 3,
      explain: "($42,000 + $18,000) ÷ ($30 − $18) = $60,000 ÷ $12 = 5,000 units. (3,500 is only the break-even point.)",
      section: "s5-4" },
    { q: "To find the sales dollars needed to earn a target profit, divide (fixed expenses + target profit) by:",
      options: ["The unit contribution margin", "The contribution margin ratio", "The selling price per unit", "The variable expense ratio"], answer: 1,
      explain: "For sales dollars use the CM ratio; for units use the unit contribution margin.",
      section: "s5-4" },
    { q: "Fixed expenses are $50,000 and the CM ratio is 25%. What sales are needed to earn a profit of $10,000?",
      options: ["$240,000", "$200,000", "$60,000", "$80,000"], answer: 0,
      explain: "($50,000 + $10,000) ÷ 25% = $240,000. ($200,000 is break-even.)",
      section: "s5-4" },

    /* ---- 5.5 ---- */
    { q: "A company plans to spend $8,000 more on advertising, expecting sales to rise by $30,000. Its CM ratio is 20%. What happens to net operating income?",
      options: ["Up $22,000", "Up $6,000", "Down $2,000", "Down $8,000"], answer: 2,
      explain: "Extra CM = $30,000 × 20% = $6,000. Minus the extra $8,000 of fixed cost: net operating income falls $2,000.",
      section: "s5-5-changes" },
    { q: "The quickest way to test a change in price, cost or volume is to:",
      options: ["Prepare a full income statement for every possible option", "Recalculate the break-even point first", "Compare total sales before and after", "Look only at the revenues and costs that change"], answer: 3,
      explain: "Incremental analysis: the change in CM minus the change in fixed costs is the change in net operating income.",
      section: "s5-5-changes" },
    { q: "Why might a company pay sales commissions on contribution margin rather than on sales?",
      options: ["Commissions based on sales revenue are not allowed under GAAP", "It steers salespeople toward the products that add most profit", "It lowers the selling price of every product that is sold", "It turns every commission into a fixed cost"], answer: 1,
      explain: "A commission on sales rewards high-priced items even when they earn little. A commission on CM rewards what adds most to profit.",
      section: "s5-5-commission" },
    { q: "A price cut drops unit CM from $10 to $8, and volume rises from 5,000 to 6,000 units. Fixed expenses stay at $40,000. What happens to net operating income?",
      options: ["Up $8,000", "Down $2,000", "No change", "Up $2,000"], answer: 1,
      explain: "Before: 5,000 × $10 − $40,000 = $10,000. After: 6,000 × $8 − $40,000 = $8,000. Net operating income falls $2,000.",
      section: "s5-5-changes" },

    /* ---- 5.6 ---- */
    { q: "On a CVP graph, the break-even point is where:",
      options: ["The sales line crosses the total expense line", "The fixed expense line crosses the vertical axis", "The total expense line is steepest", "Sales equal fixed expenses"], answer: 0,
      explain: "Where sales equal total expenses, profit is zero.",
      section: "s5-6" },
    { q: "On a CVP graph, the total expense line starts at:",
      options: ["Zero dollars, at zero units", "The fixed expenses, at zero units", "The break-even point on the sales line", "The selling price of one unit"], answer: 1,
      explain: "With zero units sold, total expenses are just the fixed expenses. The line then rises by the variable cost per unit.",
      section: "s5-6" },
    { q: "On a profit graph, the profit line:",
      options: ["Starts at zero and rises by the selling price per unit", "Starts at −fixed expenses and rises by the unit CM", "Is flat at the level of fixed expenses", "Falls as more units are sold"], answer: 1,
      explain: "With no sales the loss equals fixed expenses; each unit sold adds its contribution margin.",
      section: "s5-6" },

    /* ---- 5.7 ---- */
    { q: "Product A has sales of $60,000 with a 50% CM ratio; Product B has sales of $40,000 with a 25% CM ratio. What is the company's overall contribution margin ratio?",
      options: ["37.5%", "75%", "25%", "40%"], answer: 3,
      explain: "Total CM = $30,000 + $10,000 = $40,000 on $100,000 of sales: 40%. (37.5% is a simple average that ignores the mix.)",
      section: "s5-7" },
    { q: "If the sales mix shifts toward products with lower CM ratios, the break-even point will:",
      options: ["Rise", "Fall", "Stay the same", "Disappear"], answer: 0,
      explain: "The overall CM ratio falls, so more sales are needed to cover the same fixed expenses.",
      section: "s5-7" },
    { q: "Sales mix means:",
      options: ["The relative share of each product in total sales", "The mix of fixed and variable costs in the cost structure", "The number of customers in each region", "The ratio of cash to credit sales"], answer: 0,
      explain: "Sales mix is each product's share of total sales. Changing it changes the overall CM ratio.",
      section: "s5-7" }
  ]
};
