/* Chapter 6 quiz. Each question: q, options (4), answer (0-3), explain, section (textbook anchor id).
   All questions are original practice items; companies and numbers are fictional. */
window.QUIZ = {
  chapter: "ch6",
  title: "Chapter 6: Variable Costing and Segment Reporting",
  textbook: "textbook.html",
  questions: [
    /* ---- 6.1 ---- */
    { q: "Which cost is treated differently under absorption costing and variable costing?",
      options: ["Direct materials", "Variable selling expenses", "Fixed manufacturing overhead", "Direct labor"], answer: 2,
      explain: "Absorption costing puts fixed manufacturing overhead into each unit's cost; variable costing expenses it as a period cost. Every other cost is treated the same way.",
      section: "s6-1-unit" },
    { q: "Direct materials are $12, direct labor $8 and variable overhead $4 per unit. Fixed manufacturing overhead is $90,000 a year and 10,000 units are produced. Variable selling expense is $3 a unit. What is the unit product cost under absorption costing?",
      options: ["$24", "$27", "$33", "$36"], answer: 2,
      explain: "$12 + $8 + $4 = $24 variable manufacturing, plus $90,000 ÷ 10,000 = $9 of fixed overhead: $33. Selling expenses are never product costs.",
      section: "s6-1-unit" },
    { q: "Direct materials are $10, direct labor $6 and variable overhead $4 per unit. Fixed manufacturing overhead is $50,000 and 5,000 units are produced. Variable selling expense is $2 a unit. What is the unit product cost under variable costing?",
      options: ["$20", "$22", "$30", "$32"], answer: 0,
      explain: "Variable costing includes only variable manufacturing costs: $10 + $6 + $4 = $20.",
      section: "s6-1-unit" },
    { q: "Under variable costing, fixed manufacturing overhead is:",
      options: ["Included in the cost of each unit produced", "Added to ending inventory only", "Spread over the units sold", "Expensed in full in the period it is incurred"], answer: 3,
      explain: "Variable costing treats fixed manufacturing overhead as a period cost.",
      section: "s6-1-unit" },

    /* ---- 6.2 ---- */
    { q: "Which income statement format goes with variable costing?",
      options: ["The contribution format", "The traditional format with gross margin", "A cash-basis format", "A format with no fixed costs"], answer: 0,
      explain: "Variable costing separates variable from fixed costs, which is exactly the contribution format.",
      section: "s6-2" },
    { q: "Under absorption costing, gross margin equals:",
      options: ["Sales − variable expenses", "Sales − cost of goods sold", "Sales − all fixed costs", "Contribution margin − fixed manufacturing overhead"], answer: 1,
      explain: "The traditional format subtracts cost of goods sold (which includes fixed overhead per unit) from sales.",
      section: "s6-2" },
    { q: "Under both variable and absorption costing, variable selling and administrative expenses are:",
      options: ["Product costs included in inventory", "Ignored until the units are sold", "Period costs", "Part of fixed manufacturing overhead"], answer: 2,
      explain: "Selling and administrative costs, variable or fixed, are period costs under both methods.",
      section: "s6-2" },
    { q: "Ending inventory is 2,000 units. Variable manufacturing cost is $30 a unit and fixed manufacturing overhead is $20 a unit. What is ending inventory under absorption costing?",
      options: ["$60,000", "$40,000", "$100,000", "$50,000"], answer: 2,
      explain: "Absorption costing carries both: 2,000 × ($30 + $20) = $100,000. Under variable costing it would be $60,000.",
      section: "s6-2" },

    /* ---- 6.3 ---- */
    { q: "A company produced 20,000 units and sold 18,000. Fixed manufacturing overhead was $100,000 for the year. By how much does absorption costing net operating income exceed variable costing net operating income?",
      options: ["$100,000", "$90,000", "$10,000", "$5,000"], answer: 2,
      explain: "Fixed overhead per unit = $100,000 ÷ 20,000 = $5. Inventory grew 2,000 units, so 2,000 × $5 = $10,000 is deferred in inventory under absorption costing.",
      section: "s6-3-diff" },
    { q: "When units sold exceed units produced, net operating income is:",
      options: ["Higher under absorption costing", "Higher under variable costing", "The same under both methods", "Always negative"], answer: 1,
      explain: "Inventory shrinks, so absorption costing releases fixed overhead from earlier periods into cost of goods sold, lowering its profit.",
      section: "s6-3-diff" },
    { q: "Over several years in which total production equals total sales, the two methods report:",
      options: ["The same total net operating income", "Higher total income under absorption costing", "Higher total income under variable costing", "Different totals that never reconcile"], answer: 0,
      explain: "The methods only shift fixed overhead between periods. When inventory ends where it started, the totals match.",
      section: "s6-3-diff" },
    { q: "Why might a manager evaluated on absorption costing profit be tempted to overproduce?",
      options: ["Overproducing lowers the variable cost of each unit made", "Extra units carry fixed overhead into inventory, raising profit", "GAAP requires inventory to grow a little every single year", "Overproduction reduces the company's selling expenses"], answer: 1,
      explain: "Building inventory defers fixed overhead to later periods, so this period's absorption profit rises even if sales don't.",
      section: "s6-3-why" },
    { q: "Which is an advantage of variable costing for internal decisions?",
      options: ["It is required for income tax returns", "It always reports higher profit", "It values inventory at full cost", "It works directly with CVP analysis"], answer: 3,
      explain: "Variable costing keeps fixed costs fixed, so contribution margin, break-even and other CVP tools apply directly. Absorption costing is the one required for taxes.",
      section: "s6-3-why" },

    /* ---- 6.4 ---- */
    { q: "A traceable fixed cost of a segment is one that:",
      options: ["Varies with the segment's sales", "Would disappear if the segment were dropped", "Is shared by all segments", "Is allocated on sales dollars"], answer: 1,
      explain: "A traceable fixed cost exists because of the segment, so dropping the segment removes it.",
      section: "s6-4-trace" },
    { q: "Which is most likely a common fixed cost for a company's store segments?",
      options: ["The monthly rent on one particular store building", "Wages of a store's sales clerks", "Utilities for one store", "The salary of the company's chief executive"], answer: 3,
      explain: "The CEO serves every store, and the salary would continue if any one store closed.",
      section: "s6-4-trace" },
    { q: "A segment has sales of $300,000, variable expenses of $120,000, traceable fixed expenses of $100,000 and $40,000 of allocated common costs. What is the segment margin?",
      options: ["$180,000", "$40,000", "$80,000", "$140,000"], answer: 2,
      explain: "Segment margin = CM − traceable fixed = ($300,000 − $120,000) − $100,000 = $80,000. Allocated common costs don't belong in it.",
      section: "s6-4-margin" },
    { q: "Segment margin is the best measure of a segment's:",
      options: ["Long-run profitability", "Short-run pricing", "Cash flow this month", "Share of common costs"], answer: 0,
      explain: "It shows what the segment adds after covering every cost it causes, which is what matters for keeping or dropping it.",
      section: "s6-4-margin" },
    { q: "A fixed cost that is traceable to a division may be:",
      options: ["Common to the product lines within that division", "Traceable to every single product line inside the division", "A variable cost", "Ignored in the segment report"], answer: 0,
      explain: "A division manager's salary is traceable to the division but common to the product lines below it.",
      section: "s6-4-levels" },

    /* ---- 6.5 ---- */
    { q: "A segment's traceable fixed expenses are $90,000 and its CM ratio is 30%. What is the segment's break-even point in sales dollars?",
      options: ["$27,000", "$300,000", "$129,000", "$390,000"], answer: 1,
      explain: "Segment break-even = traceable fixed ÷ CM ratio = $90,000 ÷ 30% = $300,000.",
      section: "s6-5" },
    { q: "Total traceable fixed expenses are $150,000, common fixed expenses are $50,000 and the overall CM ratio is 40%. What is the companywide break-even point in sales dollars?",
      options: ["$375,000", "$125,000", "$200,000", "$500,000"], answer: 3,
      explain: "($150,000 + $50,000) ÷ 40% = $500,000. ($375,000 leaves out the common costs.)",
      section: "s6-5" },
    { q: "Why is a company's break-even point higher than the sum of its segments' break-even points?",
      options: ["Segments use different CM ratios", "The company must also cover common fixed costs", "Variable costs per unit are always higher at the company level", "Segment break-evens ignore traceable costs"], answer: 1,
      explain: "Each segment's break-even covers only its traceable costs. The company also has to cover the common costs.",
      section: "s6-5" },
    { q: "Segment break-even sales are computed as:",
      options: ["Traceable fixed expenses ÷ segment CM ratio", "Total fixed expenses ÷ segment CM ratio", "Traceable fixed expenses ÷ unit selling price", "Common fixed expenses ÷ overall CM ratio"], answer: 0,
      explain: "A segment breaks even when its contribution margin covers its own traceable fixed costs.",
      section: "s6-5" },

    /* ---- 6.6 ---- */
    { q: "A segment shows a loss only after allocated common costs are deducted. If it is dropped, company net operating income will:",
      options: ["Rise by the allocated common costs", "Fall by the segment margin", "Stay the same", "Rise by the segment's sales"], answer: 1,
      explain: "The common costs stay, so the company simply loses the segment's positive segment margin.",
      section: "s6-6" },
    { q: "Which is a common mistake in segment reporting?",
      options: ["Reporting contribution margin for each segment separately", "Leaving out costs such as customer service", "Separating traceable and common fixed costs", "Showing segment margin"], answer: 1,
      explain: "Segment reports should include costs from the whole value chain, not just manufacturing.",
      section: "s6-6" },
    { q: "When a cost must be assigned to segments, the allocation base should be:",
      options: ["Sales dollars, because they are easy to measure", "Whatever makes each segment look profitable", "Divided equally among all segments", "The factor that actually drives the cost"], answer: 3,
      explain: "Only a base that drives the cost gives a meaningful assignment. Sales dollars rarely drive costs.",
      section: "s6-6" }
  ]
};
