/* Chapter 3 quiz. Each question: q, options (4), answer (0-3), explain, section (textbook anchor id).
   All questions are original practice items; companies and numbers are fictional. */
window.QUIZ = {
  chapter: "ch3",
  title: "Chapter 3: Job-Order Costing: Cost Flows and External Reporting",
  textbook: "textbook.html",
  questions: [
    /* ---- 3.1 ---- */
    { q: "Which account holds the cost of jobs that have been started but not finished?",
      options: ["Raw Materials", "Work in Process", "Finished Goods", "Cost of Goods Sold"], answer: 1,
      explain: "Work in Process collects direct materials, direct labor and applied overhead for jobs still being worked on.",
      section: "s3-1-accounts" },
    { q: "Actual overhead costs, such as factory utilities and indirect labor, are recorded as:",
      options: ["Credits to Work in Process", "Debits to Cost of Goods Sold", "Credits to Manufacturing Overhead", "Debits to Manufacturing Overhead"], answer: 3,
      explain: "Actual overhead piles up on the debit side of Manufacturing Overhead. Applied overhead leaves it on the credit side.",
      section: "s3-1-accounts" },
    { q: "Manufacturing Overhead is best described as:",
      options: ["An asset that holds finished jobs", "A clearing account: actual overhead on the debit side, applied overhead on the credit side", "An expense reported on the income statement", "A liability for unpaid factory bills"], answer: 1,
      explain: "It's a temporary account. Whatever is left in it at period end is the under- or overapplied overhead.",
      section: "s3-1-accounts" },
    { q: "Selling and administrative costs flow into:",
      options: ["Work in Process", "Manufacturing Overhead", "Expense accounts for the period", "Finished Goods"], answer: 2,
      explain: "They're period costs, expensed as incurred. They never enter the inventory accounts.",
      section: "s3-1-flow" },
    { q: "Which sequence shows how product costs flow through the accounts?",
      options: ["Raw Materials → Work in Process → Finished Goods → Cost of Goods Sold", "Raw Materials → Finished Goods → Work in Process → Cost of Goods Sold", "Work in Process → Raw Materials → Finished Goods → Cost of Goods Sold", "Raw Materials → Cost of Goods Sold → Finished Goods → Work in Process"], answer: 0,
      explain: "Materials are used in production (WIP), finished jobs move to Finished Goods, and sold jobs become Cost of Goods Sold.",
      section: "s3-1-flow" },

    /* ---- 3.2 ---- */
    { q: "Indirect materials are requisitioned from the storeroom. What is the journal entry?",
      options: ["Debit Work in Process, credit Raw Materials", "Debit Manufacturing Overhead, credit Raw Materials", "Debit Raw Materials, credit Manufacturing Overhead", "Debit Finished Goods, credit Raw Materials"], answer: 1,
      explain: "Indirect materials can't be traced to jobs, so they go to Manufacturing Overhead. Direct materials would go to Work in Process.",
      section: "s3-2-materials" },
    { q: "A company began the month with $5,000 of raw materials, bought $40,000 more, and issued $36,000 to production ($30,000 direct, $6,000 indirect). What is the ending balance in Raw Materials?",
      options: ["$9,000", "$15,000", "$11,000", "$45,000"], answer: 0,
      explain: "$5,000 + $40,000 − $36,000 = $9,000. Both direct and indirect materials leave Raw Materials when they're issued.",
      section: "s3-2-materials" },
    { q: "Direct labor cost is recorded with a debit to:",
      options: ["Manufacturing Overhead", "Salaries Expense", "Work in Process", "Finished Goods"], answer: 2,
      explain: "Direct labor is traced to jobs, so it is debited to Work in Process. Indirect labor is debited to Manufacturing Overhead.",
      section: "s3-2-labor" },
    { q: "Factory utilities of $3,000 are received on account. What is the journal entry?",
      options: ["Debit Utilities Expense, credit Accounts Payable", "Debit Work in Process, credit Accounts Payable", "Debit Manufacturing Overhead, credit Accounts Payable", "Debit Manufacturing Overhead, credit Work in Process"], answer: 2,
      explain: "Factory utilities are actual overhead, so they're debited to Manufacturing Overhead. They are not a period expense, and they never go straight to Work in Process.",
      section: "s3-2-overhead" },
    { q: "Which journal entry applies overhead to jobs?",
      options: ["Debit Work in Process, credit Manufacturing Overhead", "Debit Manufacturing Overhead, credit Work in Process", "Debit Work in Process, credit Cash", "Debit Cost of Goods Sold, credit Manufacturing Overhead"], answer: 0,
      explain: "Applied overhead moves out of Manufacturing Overhead (credit) and into Work in Process (debit), at the predetermined rate × actual base.",
      section: "s3-2-overhead" },
    { q: "Depreciation on the sales office is recorded as a debit to:",
      options: ["Manufacturing Overhead", "Work in Process", "Depreciation Expense", "Finished Goods"], answer: 2,
      explain: "The sales office isn't part of the factory, so its depreciation is a period cost: an expense this period.",
      section: "s3-2-nonmfg" },
    { q: "When jobs are completed, the journal entry is:",
      options: ["Debit Finished Goods, credit Work in Process", "Debit Cost of Goods Sold, credit Finished Goods", "Debit Work in Process, credit Finished Goods", "Debit Finished Goods, credit Cost of Goods Sold"], answer: 0,
      explain: "Completed jobs move out of Work in Process and into Finished Goods. The COGS entry happens later, when they're sold.",
      section: "s3-2-complete" },
    { q: "Work in Process began at $10,000. During the month it received $25,000 of direct materials, $30,000 of direct labor and $15,000 of applied overhead. Jobs costing $70,000 were completed. What is ending Work in Process?",
      options: ["$80,000", "$10,000", "$70,000", "$0"], answer: 1,
      explain: "$10,000 + $25,000 + $30,000 + $15,000 − $70,000 = $10,000.",
      section: "s3-2-complete" },

    /* ---- 3.3 ---- */
    { q: "Beginning raw materials were $6,000, purchases $35,000 and ending raw materials $7,000. Indirect materials used were $3,000. How much direct materials cost was used in production?",
      options: ["$34,000", "$41,000", "$31,000", "$28,000"], answer: 2,
      explain: "Raw materials used = $6,000 + $35,000 − $7,000 = $34,000. Subtract the $3,000 of indirect materials: direct materials = $31,000.",
      section: "s3-3-cogm" },
    { q: "Direct materials were $31,000, direct labor $50,000 and overhead applied $40,000. Work in process was $12,000 at the start and $15,000 at the end. What is cost of goods manufactured?",
      options: ["$121,000", "$124,000", "$133,000", "$118,000"], answer: 3,
      explain: "Total manufacturing costs = $31,000 + $50,000 + $40,000 = $121,000. Add beginning WIP and subtract ending WIP: $121,000 + $12,000 − $15,000 = $118,000.",
      section: "s3-3-cogm" },
    { q: "Direct materials were $20,000, direct labor $35,000, overhead applied $28,000 and actual overhead $30,000. What are total manufacturing costs?",
      options: ["$85,000", "$83,000", "$55,000", "$113,000"], answer: 1,
      explain: "Use applied overhead: $20,000 + $35,000 + $28,000 = $83,000. Actual overhead never appears on the schedule.",
      section: "s3-3-cogm" },
    { q: "On the schedule of cost of goods manufactured, manufacturing overhead is shown at:",
      options: ["Actual overhead incurred", "Estimated overhead for the year", "Overhead applied to Work in Process", "The underapplied amount"], answer: 2,
      explain: "The schedule follows Work in Process, and only applied overhead enters Work in Process.",
      section: "s3-3-cogm" },
    { q: "Cost of goods manufactured is the cost of:",
      options: ["Materials purchased during the period", "Jobs completed during the period", "Jobs sold during the period", "All manufacturing costs incurred during the period"], answer: 1,
      explain: "It's the amount moved from Work in Process to Finished Goods, so it counts jobs completed, whether or not they were sold.",
      section: "s3-3-cogm" },
    { q: "Finished goods were $20,000 at the start and $30,000 at the end. Cost of goods manufactured was $100,000, and overhead was underapplied by $3,000. What is the adjusted cost of goods sold?",
      options: ["$87,000", "$90,000", "$120,000", "$93,000"], answer: 3,
      explain: "Unadjusted COGS = $20,000 + $100,000 − $30,000 = $90,000. Underapplied overhead is added: $90,000 + $3,000 = $93,000.",
      section: "s3-3-cogs" },

    /* ---- 3.4 ---- */
    { q: "Actual overhead for the year was $185,000 and overhead applied to jobs was $192,000. What was the overhead balance at year end?",
      options: ["$7,000 underapplied", "$7,000 overapplied", "$0", "$377,000 overapplied"], answer: 1,
      explain: "Applied ($192,000) is more than actual ($185,000), so Manufacturing Overhead has a $7,000 credit balance: overapplied.",
      section: "s3-4-compute" },
    { q: "A debit balance in Manufacturing Overhead at year end means overhead was:",
      options: ["Underapplied", "Overapplied", "Exactly applied", "Never applied"], answer: 0,
      explain: "Debits are actual and credits are applied. A debit balance means actual was more than applied: underapplied.",
      section: "s3-4-compute" },
    { q: "Closing overapplied overhead to Cost of Goods Sold:",
      options: ["Increases cost of goods sold", "Has no effect on cost of goods sold", "Increases Finished Goods", "Decreases cost of goods sold"], answer: 3,
      explain: "Jobs were overcosted, so cost of goods sold is reduced (debit Manufacturing Overhead, credit Cost of Goods Sold).",
      section: "s3-4-close" },
    { q: "Overhead was underapplied by $4,000, and the company closes it to Cost of Goods Sold. What is the journal entry?",
      options: ["Debit Manufacturing Overhead $4,000; credit Cost of Goods Sold $4,000", "Debit Work in Process $4,000; credit Manufacturing Overhead $4,000", "Debit Finished Goods $4,000; credit Cost of Goods Sold $4,000", "Debit Cost of Goods Sold $4,000; credit Manufacturing Overhead $4,000"], answer: 3,
      explain: "The $4,000 debit balance is cleared with a credit to Manufacturing Overhead, and cost of goods sold goes up by $4,000.",
      section: "s3-4-close" },
    { q: "Under the allocation method, an under- or overapplied balance is spread over:",
      options: ["Work in Process, Finished Goods and Cost of Goods Sold", "Raw Materials, Work in Process and Finished Goods", "Manufacturing Overhead, Work in Process and Finished Goods", "Sales, Cost of Goods Sold and Finished Goods"], answer: 0,
      explain: "Those are the three places applied overhead ended up, so each takes its share of the correction.",
      section: "s3-4-allocate" },
    { q: "Overhead was underapplied by $6,000. Of the overhead applied during the year, 20% is in ending Work in Process, 25% in ending Finished Goods and 55% in Cost of Goods Sold. Using the allocation method, how much of the underapplied overhead goes to Finished Goods?",
      options: ["$1,200", "$3,300", "$6,000", "$1,500"], answer: 3,
      explain: "25% × $6,000 = $1,500. Work in Process gets $1,200 and Cost of Goods Sold gets $3,300.",
      section: "s3-4-allocate" }
  ]
};
