/* Chapter 2 quiz. Each question: q, options (4), answer (0-3), explain, section (textbook anchor id).
   All questions are original practice items; companies and numbers are fictional. */
window.QUIZ = {
  chapter: "ch2",
  title: "Chapter 2: Job-Order Costing",
  textbook: "textbook.html",
  questions: [
    /* ---- 2.1 ---- */
    { q: "Which company is most likely to use job-order costing?",
      options: ["A breakfast cereal maker", "A custom yacht builder", "An oil refinery", "A bottled-water plant"], answer: 1,
      explain: "Each yacht is built to a customer's order and is different from the last, so its costs must be tracked job by job. The others make one identical product continuously (process costing).",
      section: "s2-1-when" },
    { q: "Which document charges direct materials to a specific job?",
      options: ["Employee time ticket", "Bill of lading", "Materials requisition form", "Purchase order"], answer: 2,
      explain: "A materials requisition form takes materials out of the storeroom and names the job they're for, so the cost goes straight onto that job cost sheet.",
      section: "s2-1-sheet" },
    { q: "Which document records how many hours a worker spent on each job?",
      options: ["Employee time ticket", "Materials requisition form", "Sales invoice", "Bill of materials"], answer: 0,
      explain: "The time ticket logs a worker's hours job by job, which is how direct labor is charged to each job.",
      section: "s2-1-sheet" },
    { q: "On a job cost sheet, manufacturing overhead is:",
      options: ["Traced directly from the overhead invoices", "Recorded only when the job is sold", "Left off the job cost sheet", "Applied using a predetermined overhead rate"], answer: 3,
      explain: "Overhead can't be traced to individual jobs, so it is applied with a predetermined rate. Direct materials and direct labor are the traced costs.",
      section: "s2-1-sheet" },

    /* ---- 2.2 ---- */
    { q: "The predetermined overhead rate is computed:",
      options: ["Before the year begins, using estimates", "At the end of the year, using actual costs", "Each month, using that month's actual overhead", "When each job is finished"], answer: 0,
      explain: "\"Predetermined\" means it is set in advance, from estimated overhead and an estimated amount of the allocation base.",
      section: "s2-2-base" },
    { q: "A company estimates fixed overhead of $240,000, variable overhead of $4 per machine-hour, and 30,000 machine-hours for the year. What is the predetermined overhead rate?",
      options: ["$8 per machine-hour", "$16 per machine-hour", "$4 per machine-hour", "$12 per machine-hour"], answer: 3,
      explain: "Estimated total overhead = $240,000 + $4 × 30,000 = $360,000. Rate = $360,000 ÷ 30,000 machine-hours = $12 per machine-hour.",
      section: "s2-2-compute" },
    { q: "Why do companies apply overhead with a predetermined rate instead of waiting for actual figures?",
      options: ["GAAP doesn't allow actual overhead to be used in job costs", "A predetermined rate always ends up equal to actual overhead", "Actual overhead isn't known until year end, but job costs are needed now", "It removes the need to track direct labor on time tickets"], answer: 2,
      explain: "Managers need job costs during the year for pricing and inventory. Actual overhead also swings from month to month, which would make similar jobs cost different amounts.",
      section: "s2-2-base" },
    { q: "A company estimated $500,000 of overhead and 25,000 direct labor-hours for the year. Actual overhead turned out to be $546,000 over 26,000 hours. What predetermined overhead rate did it use during the year?",
      options: ["$21 per direct labor-hour", "$20 per direct labor-hour", "$21.84 per direct labor-hour", "$19.23 per direct labor-hour"], answer: 1,
      explain: "The rate uses estimates only: $500,000 ÷ 25,000 = $20 per direct labor-hour. The actual figures matter later, when comparing applied with actual overhead.",
      section: "s2-2-compute" },

    /* ---- 2.3 ---- */
    { q: "Overhead applied to a job equals:",
      options: ["Actual overhead ÷ actual hours", "Predetermined rate × estimated hours for the year", "Predetermined rate × actual hours used by the job", "Actual overhead × the job's share of sales"], answer: 2,
      explain: "Applied overhead combines an estimated rate with the job's actual use of the base.",
      section: "s2-3-apply" },
    { q: "The predetermined overhead rate is $12 per machine-hour. Job 77 used 100 machine-hours and 80 direct labor-hours. How much overhead is applied to Job 77?",
      options: ["$1,000", "$960", "$400", "$1,200"], answer: 3,
      explain: "The base is machine-hours, so use the job's machine-hours: 100 × $12 = $1,200. Its labor-hours don't matter here.",
      section: "s2-3-apply" },
    { q: "A company applies overhead at $15 per direct labor-hour. In March, Job X used 40 direct labor-hours and Job Y used 60. How much overhead was applied to the two jobs together?",
      options: ["$600", "$900", "$1,500", "$2,400"], answer: 2,
      explain: "(40 + 60) hours × $15 = $1,500: $600 to Job X and $900 to Job Y.",
      section: "s2-3-apply" },

    /* ---- 2.4 ---- */
    { q: "Job 52 used $1,500 of direct materials and 50 direct labor-hours at $18 an hour. Overhead is applied at $34 per direct labor-hour. What is the total cost of Job 52?",
      options: ["$2,400", "$4,100", "$3,200", "$5,800"], answer: 1,
      explain: "Direct labor = 50 × $18 = $900. Overhead = 50 × $34 = $1,700. Total = $1,500 + $900 + $1,700 = $4,100.",
      section: "s2-4-total" },
    { q: "Job 52 (total cost $4,100) produced 100 units. What is the unit product cost of Job 52?",
      options: ["$41", "$24", "$17", "$58"], answer: 0,
      explain: "Unit product cost = total job cost ÷ units = $4,100 ÷ 100 = $41.",
      section: "s2-4-total" },
    { q: "Total job cost is made up of:",
      options: ["Direct materials and direct labor only", "Direct materials, direct labor and actual overhead", "Direct materials, direct labor and applied overhead", "Direct labor and applied overhead only"], answer: 2,
      explain: "A job carries its traced direct materials and direct labor plus the overhead applied to it. Actual overhead never goes onto individual jobs.",
      section: "s2-4-total" },
    { q: "Which makes the best allocation base for overhead?",
      options: ["Whatever is easiest to measure", "A cost driver that actually causes overhead", "The number of customers", "Sales revenue"], answer: 1,
      explain: "The base should drive overhead. Otherwise some jobs get too much overhead and others too little.",
      section: "s2-4-base" },
    { q: "A shop's overhead comes mostly from its machines, but it applies overhead using direct labor-hours. Jobs that need lots of hand labor but little machine time will be:",
      options: ["Undercosted", "Costed accurately", "Unaffected", "Overcosted"], answer: 3,
      explain: "Those jobs use many labor-hours, so they soak up lots of overhead even though they cause little of it. They end up overcosted, and machine-heavy jobs undercosted.",
      section: "s2-4-base" },

    /* ---- 2.5 ---- */
    { q: "The Milling Department applies overhead at $9 per machine-hour. Job 9 used 50 machine-hours and 20 direct labor-hours in Milling. How much overhead does the Milling Department apply to Job 9?",
      options: ["$630", "$180", "$450", "$270"], answer: 2,
      explain: "Milling's base is machine-hours: 50 × $9 = $450. Job 9's labor-hours aren't Milling's base.",
      section: "s2-5-depts" },
    { q: "Why might a company use departmental overhead rates instead of a single plantwide rate?",
      options: ["To cut down on recordkeeping in the accounting office", "Because its departments have different overhead drivers", "Because GAAP requires one rate per department", "To make applied overhead exactly equal actual overhead"], answer: 1,
      explain: "If one department's overhead is driven by machines and another's by labor, separate rates with separate bases cost jobs more accurately.",
      section: "s2-5-depts" },
    { q: "Job 15 has a total cost of $6,000. The company prices jobs at cost plus a 40% markup. What price does it quote?",
      options: ["$8,400", "$2,400", "$6,400", "$10,000"], answer: 0,
      explain: "$6,000 × 1.40 = $8,400. If the job's cost is wrong, so is the price.",
      section: "s2-5-price" },
    { q: "Assigning overhead with a separate rate for each activity, such as setups and inspections, is called:",
      options: ["Process costing", "Absorption costing", "Activity-based costing", "Variable costing"], answer: 2,
      explain: "Activity-based costing (Chapter 7) takes multiple rates further, using one rate per activity.",
      section: "s2-5-price" },

    /* ---- 2.6 ---- */
    { q: "At year end, Job A ($5,000) has been sold, Job B ($7,000) is finished but unsold, and Jobs C ($2,500) and D ($3,500) are still being worked on. What is the ending balance in Work in Process?",
      options: ["$13,000", "$2,500", "$8,500", "$6,000"], answer: 3,
      explain: "Work in process holds the unfinished jobs: $2,500 + $3,500 = $6,000. Job B is in finished goods and Job A is in cost of goods sold.",
      section: "s2-6-ledger" },
    { q: "A company applied overhead at $10 per direct labor-hour and its workers logged 31,500 hours. Actual overhead was $300,000. By how much was overhead underapplied or overapplied?",
      options: ["$15,000 underapplied", "$15,000 overapplied", "$5,000 overapplied", "$0"], answer: 1,
      explain: "Applied = 31,500 × $10 = $315,000. That's more than the $300,000 actual, so overhead was overapplied by $15,000.",
      section: "s2-6-under" },
    { q: "Underapplied overhead means:",
      options: ["Applied overhead was more than actual overhead", "The predetermined rate was set too high", "Jobs were charged too much overhead", "Actual overhead was more than applied overhead"], answer: 3,
      explain: "Underapplied: the jobs received less overhead than was actually incurred, so they were undercosted.",
      section: "s2-6-under" },
    { q: "When underapplied overhead is closed out to cost of goods sold, cost of goods sold:",
      options: ["Increases", "Decreases", "Doesn't change", "Becomes zero"], answer: 0,
      explain: "The jobs were charged too little, so the shortfall is added to cost of goods sold. Overapplied overhead does the opposite.",
      section: "s2-6-under" },
    { q: "A law firm uses job-order costing. For the firm, a \"job\" is most likely:",
      options: ["Each client's case", "Each office building", "Each calendar year", "Each lawyer's salary"], answer: 0,
      explain: "Service firms treat each client engagement as a job: lawyers' hours are direct labor and office overhead is applied with a rate.",
      section: "s2-6-service" }
  ]
};
