/* Chapter 4 quiz. Each question: q, options (4), answer (0-3), explain, section (textbook anchor id).
   All questions are original practice items; companies and numbers are fictional. */
window.QUIZ = {
  chapter: "ch4",
  title: "Chapter 4: Process Costing",
  textbook: "textbook.html",
  questions: [
    /* ---- 4.1 ---- */
    { q: "Which company would most likely use process costing?",
      options: ["A custom furniture maker taking orders", "A bottled iced-tea producer", "An architecture firm", "A wedding photographer"], answer: 1,
      explain: "Iced tea is one identical product made continuously, so costs are collected by department. The others do unique jobs.",
      section: "s4-1-compare" },
    { q: "In process costing, manufacturing costs are collected by:",
      options: ["Job", "Customer order", "Department", "Sales territory"], answer: 2,
      explain: "Every unit passing through a department gets the same work, so costs are gathered by department for the period.",
      section: "s4-1-compare" },
    { q: "Which statement is true of both job-order costing and process costing?",
      options: ["Both use a job cost sheet for every unit they make", "Both collect costs by processing department only, never by job", "Both use the same manufacturing accounts, such as Work in Process", "Both leave manufacturing overhead out of the cost of a unit"], answer: 2,
      explain: "The accounts and the flow of costs are the same. What differs is whether costs are collected by job or by department.",
      section: "s4-1-compare" },
    { q: "Conversion cost equals:",
      options: ["Direct materials + direct labor", "Direct labor + manufacturing overhead", "Direct materials + manufacturing overhead", "Total manufacturing cost − direct labor"], answer: 1,
      explain: "Conversion cost is the cost of turning materials into product: direct labor plus manufacturing overhead.",
      section: "s4-1-depts" },
    { q: "A processing department is best described as:",
      options: ["A part of the factory that adds cost to the product, treating every unit alike", "The sales office that takes customer orders and sets prices", "A department that handles only one-of-a-kind custom orders, each costed on its own sheet", "The accounting office that keeps a job cost sheet for each order"], answer: 0,
      explain: "Processing departments add cost to the product, and their output is identical from unit to unit.",
      section: "s4-1-depts" },

    /* ---- 4.2 ---- */
    { q: "In a process costing system, direct labor is recorded with a debit to:",
      options: ["Work in Process for the department where the work was done", "Manufacturing Overhead, to be applied later at a predetermined rate", "Finished Goods, since labor is what finishes the product", "Cost of Goods Sold for the period"], answer: 0,
      explain: "Labor is traced to departments, not jobs, so each department's own Work in Process account is debited.",
      section: "s4-2-inputs" },
    { q: "Units move from the Mixing department to the Packaging department. What is the journal entry?",
      options: ["Debit Work in Process–Mixing, credit Work in Process–Packaging", "Debit Finished Goods, credit Work in Process–Mixing", "Debit Work in Process–Packaging, credit Work in Process–Mixing", "Debit Cost of Goods Sold, credit Work in Process–Packaging"], answer: 2,
      explain: "The cost follows the units: it leaves Mixing (credit) and enters Packaging (debit).",
      section: "s4-2-transfers" },
    { q: "Transferred-in cost is:",
      options: ["The cost of materials bought from outside suppliers this period", "The cost of units received from an earlier department", "Overhead applied by the last department", "Another name for cost of goods sold"], answer: 1,
      explain: "When units arrive from an earlier department, their cost comes with them and is treated as an input of the receiving department.",
      section: "s4-2-transfers" },
    { q: "A company with two processing departments will usually have:",
      options: ["One Work in Process account shared by the whole factory", "No Work in Process account", "A job cost sheet for each unit", "A separate Work in Process account for each department"], answer: 3,
      explain: "Each processing department keeps its own Work in Process account, and costs move between them as units move.",
      section: "s4-2-inputs" },

    /* ---- 4.3 ---- */
    { q: "A department had no beginning inventory, started 20,000 units, and completed and transferred 16,000. The 4,000 units in ending work in process are 25% complete with respect to conversion. What were the equivalent units of production for conversion?",
      options: ["16,000", "20,000", "17,000", "1,000"], answer: 2,
      explain: "16,000 completed + (4,000 × 25%) = 16,000 + 1,000 = 17,000 equivalent units.",
      section: "s4-3-wa" },
    { q: "How many equivalent units are in 3,000 units that are 40% complete?",
      options: ["3,000", "1,200", "1,800", "7,500"], answer: 1,
      explain: "3,000 × 40% = 1,200. The work in 3,000 units that are 40% done could have finished 1,200 whole units.",
      section: "s4-3-idea" },
    { q: "Under the weighted-average method, equivalent units of production equal:",
      options: ["Units started this period only", "Units in beginning work in process + units started this period", "Units completed − the equivalent units in beginning work in process", "Units completed and transferred out + equivalent units in ending WIP"], answer: 3,
      explain: "Weighted-average counts every completed unit as whole, then adds the work sitting in ending inventory.",
      section: "s4-3-wa" },
    { q: "Under the weighted-average method, the percent complete of beginning work in process:",
      options: ["Is added to the equivalent units for the period", "Is subtracted from the equivalent units", "Does not enter the equivalent-unit calculation", "Is used for materials only"], answer: 2,
      explain: "Beginning units that were finished are simply part of the units completed. Their earlier percent complete doesn't matter under weighted-average.",
      section: "s4-3-wa" },
    { q: "A department began the month with 3,000 units in process, started 27,000 units, and ended with 5,000 units in process. How many units were completed and transferred out?",
      options: ["30,000", "25,000", "22,000", "35,000"], answer: 1,
      explain: "Units to account for: 3,000 + 27,000 = 30,000. Subtract the 5,000 still in process: 25,000 were completed and transferred.",
      section: "s4-3-wa" },

    /* ---- 4.4 ---- */
    { q: "Beginning work in process held $5,000 of materials cost, and $43,000 of materials were added this period. Equivalent units for materials were 24,000. What is the cost per equivalent unit for materials?",
      options: ["$1.79", "$2.00", "$0.21", "$2.20"], answer: 1,
      explain: "Weighted-average adds beginning cost to cost added: ($5,000 + $43,000) ÷ 24,000 = $48,000 ÷ 24,000 = $2.00.",
      section: "s4-4" },
    { q: "Under the weighted-average method, the cost per equivalent unit is computed with:",
      options: ["Only the costs added during this period, leaving out beginning inventory", "Only the cost of beginning work in process carried over", "Cost of goods sold divided by units sold during the period", "The cost of beginning work in process plus the costs added this period"], answer: 3,
      explain: "Weighted-average blends last period's cost in beginning inventory with this period's cost, then divides by equivalent units.",
      section: "s4-4" },
    { q: "Materials cost per equivalent unit is $3.20 and conversion cost per equivalent unit is $1.80. What is the cost of one fully completed unit?",
      options: ["$1.40", "$3.20", "$5.76", "$5.00"], answer: 3,
      explain: "A finished unit has all of its materials and all of its conversion: $3.20 + $1.80 = $5.00.",
      section: "s4-4" },
    { q: "A student divides total materials cost by the equivalent units for conversion. What is wrong?",
      options: ["Nothing; that's the standard formula for every category", "Materials cost should be divided by units started instead of EU", "Conversion units should be used for every cost category", "Each cost category must be divided by its own equivalent units"], answer: 3,
      explain: "Materials and conversion are added at different rates, so each category has its own equivalent units and its own cost per unit.",
      section: "s4-4" },

    /* ---- 4.5 ---- */
    { q: "15,000 units were completed and transferred. Cost per equivalent unit was $3.00 for materials and $5.00 for conversion. What cost was transferred out?",
      options: ["$45,000", "$75,000", "$120,000", "$135,000"], answer: 2,
      explain: "Completed units are 100% done for both categories: 15,000 × ($3.00 + $5.00) = $120,000.",
      section: "s4-5-assign" },
    { q: "The 2,000 units in ending work in process are 100% complete for materials and 40% complete for conversion. Cost per equivalent unit is $3.00 for materials and $5.00 for conversion. What is the cost of ending work in process?",
      options: ["$16,000", "$10,000", "$6,000", "$6,400"], answer: 1,
      explain: "Materials: 2,000 × $3.00 = $6,000. Conversion: (2,000 × 40%) × $5.00 = 800 × $5.00 = $4,000. Total $10,000.",
      section: "s4-5-assign" },
    { q: "Beginning work in process cost $8,000, and $72,000 of costs were added during the period. Units transferred out cost $70,000. What were the total costs to be accounted for?",
      options: ["$80,000", "$72,000", "$10,000", "$150,000"], answer: 0,
      explain: "Costs to account for = beginning cost + cost added = $8,000 + $72,000 = $80,000. (Ending work in process would be $10,000.)",
      section: "s4-5-recon" },
    { q: "A cost reconciliation report shows that:",
      options: ["Beginning WIP cost + cost added = cost transferred out + ending WIP cost", "Sales − cost of goods sold = gross margin for the period", "Actual overhead equals overhead applied for the period", "Units started during the period always equal the units completed and transferred"], answer: 0,
      explain: "It proves every dollar the department had to account for was assigned either to units transferred out or to ending inventory.",
      section: "s4-5-recon" },

    /* ---- 4.6 ---- */
    { q: "Operation costing is best described as:",
      options: ["A hybrid: materials traced to batches, conversion costs averaged by operation", "Another name for process costing, used by refineries and mills", "A version of job-order costing in which every cost, including conversion, is traced to each batch", "A method that leaves conversion costs out of product cost entirely"], answer: 0,
      explain: "It borrows from both systems: batch-by-batch materials, and one conversion rate per operation.",
      section: "s4-6" },
    { q: "In operation costing, which cost is usually traced to each batch?",
      options: ["Materials", "Conversion cost", "Selling costs", "Administrative costs"], answer: 0,
      explain: "Materials differ from batch to batch, so they're traced to batches. Conversion work is about the same per unit, so it's averaged.",
      section: "s4-6" },
    { q: "Which business is the best fit for operation costing?",
      options: ["A refinery producing a single grade of fuel around the clock, every gallon identical", "A shirt factory running batches of different styles through the same cutting and sewing steps", "A law firm billing each client by the hours spent on that client's case", "A yacht builder making one custom boat a year to each buyer's own design"], answer: 1,
      explain: "Different batches (different materials) going through the same operations (same conversion work) is the classic case for operation costing.",
      section: "s4-6" }
  ]
};
